### ISSUE TITLE
issue on loading

### ISSUE THREAD

**Issue by vokshirg** [glyph-fr/capistrano-dotenv-tasks#8] opened 2016-07-13 06:56 UTC
Hello) it's appear when I try start server

```
.rvm/gems/ruby-2.3.1@kcs/gems/capistrano-dotenv-tasks-0.1.3/lib/capistrano/dotenv/tasks.rb:6:in `<top (required)>': undefined method `set' for main:Object (NoMethodError)
Did you mean?  send
```

**Comment by vala** [comment] 2016-07-13 08:25
In your Gemfile, can you try changing the `gem 'capistrano-dotenv-tasks'` line to : 

``` ruby
gem 'capistrano-dotenv-tasks', require: false
```

I just saw that this is not documented in the README, I'll update it

**Comment by vala** [comment] 2016-07-13 10:31
I updated the README (5562e122857038fe3229709c33ec7c36153de820).

@vokshirg did this solve your problem, if yes, please close the issue

**Comment by vala** [comment] 2016-07-13 10:33
Note that this is a duplicate of past closed issue here : https://github.com/glyph-fr/capistrano-dotenv-tasks/issues/4

**Comment by vala** [comment] 2016-11-28 11:26
Closing since @vokshirg did not answer several months after !

**Closed as completed by vala** 2016-11-28 11:26 UTC
